import type {
  MoveAvoidArea,
  MoveEquipmentType,
  MoveExperience,
  MoveFocus,
  MoveIntensity,
} from './adaptation';

export type MovePattern =
  | 'squat'
  | 'hinge'
  | 'lunge'
  | 'push'
  | 'pull'
  | 'core'
  | 'conditioning'
  | 'mobility';

export type MoveImpact = 'low' | 'medium' | 'high';

export type MoveExercise = {
  id: string;
  icon: string;
  title: string;
  cue: string;
  easier: string;
  swapWith: string;
  needs: 'none' | 'chair' | 'floor';
  focus: MoveFocus[];
  areas: MoveAvoidArea[];
  equipment?: MoveEquipmentType[];
  minExperience?: Exclude<MoveExperience, 'sin_definir'>;
  minIntensity?: MoveIntensity;
  pattern: MovePattern;
  family: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  impact: MoveImpact;
};

export const MOVE_PATTERN_LABELS: Record<MovePattern, string> = {
  squat: 'Sentadilla',
  hinge: 'Cadera / bisagra',
  lunge: 'Zancada / unilateral',
  push: 'Empuje',
  pull: 'Tirón',
  core: 'Core / estabilidad',
  conditioning: 'Condición',
  mobility: 'Movilidad',
};

export const MOVE_EXERCISE_LIBRARY: MoveExercise[] = [
  // Squat / knee dominant
  { id: 'chair-rise', icon: '🪑', title: 'Sentarse y levantarse', cue: 'Desde una silla firme, ponte de pie y vuelve con control.', easier: 'Usa las manos como apoyo y reduce el recorrido.', swapWith: 'squat', needs: 'chair', focus: ['equilibrado', 'fuerza'], areas: ['knees', 'lowerBack'], pattern: 'squat', family: 'squat', difficulty: 1, impact: 'low' },
  { id: 'squat', icon: '🏋️', title: 'Sentadilla controlada', cue: 'Lleva la cadera atrás, baja a un rango cómodo y vuelve empujando el suelo.', easier: 'Baja menos o usa una silla como referencia.', swapWith: 'chair-rise', needs: 'none', focus: ['fuerza', 'equilibrado'], areas: ['knees', 'lowerBack'], pattern: 'squat', family: 'squat', difficulty: 2, impact: 'low' },
  { id: 'tempo-squat', icon: '⏱️', title: 'Sentadilla con tempo', cue: 'Baja lentamente, pausa un instante y sube manteniendo el control.', easier: 'Vuelve a una sentadilla a ritmo natural.', swapWith: 'squat', needs: 'none', focus: ['fuerza'], areas: ['knees', 'lowerBack'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'squat', family: 'squat', difficulty: 3, impact: 'low' },
  { id: 'pause-squat', icon: '⏸️', title: 'Sentadilla con pausa', cue: 'Pausa brevemente en un rango cómodo antes de volver a subir.', easier: 'Reduce la pausa o vuelve a sentadilla normal.', swapWith: 'tempo-squat', needs: 'none', focus: ['fuerza'], areas: ['knees', 'lowerBack'], minExperience: 'avanzado', minIntensity: 'moderada', pattern: 'squat', family: 'squat', difficulty: 4, impact: 'low' },
  { id: 'db-goblet-squat', icon: '🏋️', title: 'Sentadilla goblet con mancuerna', cue: 'Sujeta una mancuerna cerca del pecho y haz una sentadilla controlada.', easier: 'Reduce profundidad o cambia a sentadilla sin carga.', swapWith: 'squat', needs: 'none', focus: ['fuerza', 'equilibrado'], areas: ['knees', 'lowerBack'], equipment: ['dumbbells'], minIntensity: 'suave', pattern: 'squat', family: 'squat', difficulty: 3, impact: 'low' },
  { id: 'kb-goblet-squat', icon: '🔔', title: 'Sentadilla goblet con kettlebell', cue: 'Sujeta la kettlebell cerca del pecho y baja con control.', easier: 'Baja menos o cambia a sentadilla sin carga.', swapWith: 'squat', needs: 'none', focus: ['fuerza'], areas: ['knees', 'lowerBack'], equipment: ['kettlebell'], minIntensity: 'moderada', pattern: 'squat', family: 'squat', difficulty: 3, impact: 'low' },
  { id: 'db-front-squat', icon: '🏋️', title: 'Sentadilla frontal con mancuernas', cue: 'Sostén las mancuernas a la altura de los hombros y baja manteniendo el tronco estable.', easier: 'Vuelve a goblet o reduce el recorrido.', swapWith: 'db-goblet-squat', needs: 'none', focus: ['fuerza'], areas: ['knees', 'lowerBack', 'shoulders'], equipment: ['dumbbells'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'squat', family: 'squat', difficulty: 4, impact: 'low' },
  { id: 'barbell-back-squat', icon: '🏋️', title: 'Sentadilla con barra', cue: 'Con la barra cargada según tu registro, haz una sentadilla estable y controlada.', easier: 'Cambia a goblet o sentadilla sin carga.', swapWith: 'db-goblet-squat', needs: 'none', focus: ['fuerza'], areas: ['knees', 'lowerBack', 'shoulders'], equipment: ['barbell'], minExperience: 'avanzado', minIntensity: 'alta', pattern: 'squat', family: 'squat', difficulty: 5, impact: 'low' },
  { id: 'machine-leg-press', icon: '⚙️', title: 'Prensa de piernas', cue: 'Empuja la plataforma sin bloquear las rodillas y vuelve con control.', easier: 'Reduce recorrido o resistencia.', swapWith: 'chair-rise', needs: 'none', focus: ['fuerza'], areas: ['knees', 'lowerBack'], equipment: ['machine'], minIntensity: 'moderada', pattern: 'squat', family: 'squat', difficulty: 3, impact: 'low' },

  // Hinge / posterior chain
  { id: 'hip-hinge', icon: '↘️', title: 'Bisagra de cadera', cue: 'Lleva la cadera atrás con la espalda larga y vuelve apretando glúteos.', easier: 'Reduce el recorrido y apoya las manos en los muslos.', swapWith: 'bridge', needs: 'none', focus: ['fuerza', 'equilibrado'], areas: ['lowerBack'], pattern: 'hinge', family: 'hinge', difficulty: 1, impact: 'low' },
  { id: 'bridge', icon: '🌉', title: 'Puente de cadera', cue: 'Boca arriba, eleva la cadera con control y vuelve sin dejarla caer.', easier: 'Haz un recorrido más corto.', swapWith: 'hip-hinge', needs: 'floor', focus: ['fuerza', 'equilibrado'], areas: ['knees', 'lowerBack'], pattern: 'hinge', family: 'hinge', difficulty: 1, impact: 'low' },
  { id: 'kb-deadlift', icon: '🔔', title: 'Peso muerto con kettlebell', cue: 'Lleva la cadera atrás, toma la kettlebell y ponte de pie con control.', easier: 'Reduce recorrido o cambia a bisagra sin carga.', swapWith: 'hip-hinge', needs: 'none', focus: ['fuerza', 'equilibrado'], areas: ['knees', 'lowerBack'], equipment: ['kettlebell'], minIntensity: 'suave', pattern: 'hinge', family: 'hinge', difficulty: 2, impact: 'low' },
  { id: 'db-rdl', icon: '🏋️', title: 'Peso muerto rumano con mancuernas', cue: 'Desliza las mancuernas cerca de las piernas mientras llevas la cadera atrás.', easier: 'Reduce recorrido o cambia a bisagra sin carga.', swapWith: 'hip-hinge', needs: 'none', focus: ['fuerza'], areas: ['lowerBack'], equipment: ['dumbbells'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'hinge', family: 'hinge', difficulty: 3, impact: 'low' },
  { id: 'hip-thrust-bench', icon: '🛋️', title: 'Hip thrust en banco', cue: 'Apoya la espalda alta en el banco y eleva la cadera sin hiperextender la espalda.', easier: 'Haz puente en el suelo.', swapWith: 'bridge', needs: 'none', focus: ['fuerza'], areas: ['lowerBack'], equipment: ['bench'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'hinge', family: 'hinge', difficulty: 3, impact: 'low' },
  { id: 'barbell-rdl', icon: '🏋️', title: 'Peso muerto rumano con barra', cue: 'Lleva la barra cerca de las piernas y haz la bisagra con control.', easier: 'Cambia a mancuernas o bisagra sin carga.', swapWith: 'db-rdl', needs: 'none', focus: ['fuerza'], areas: ['lowerBack'], equipment: ['barbell'], minExperience: 'avanzado', minIntensity: 'alta', pattern: 'hinge', family: 'hinge', difficulty: 4, impact: 'low' },
  { id: 'machine-leg-curl', icon: '⚙️', title: 'Curl femoral en máquina', cue: 'Flexiona las rodillas contra la resistencia sin despegar el cuerpo del apoyo.', easier: 'Reduce resistencia o recorrido.', swapWith: 'bridge', needs: 'none', focus: ['fuerza'], areas: ['knees'], equipment: ['machine'], minIntensity: 'moderada', pattern: 'hinge', family: 'hinge', difficulty: 2, impact: 'low' },

  // Lunge / unilateral
  { id: 'supported-split-squat', icon: '🪑', title: 'Split squat con apoyo', cue: 'Usa una silla o pared para estabilizarte y baja en un rango cómodo.', easier: 'Acorta la postura y baja menos.', swapWith: 'chair-rise', needs: 'chair', focus: ['fuerza', 'equilibrado'], areas: ['knees'], pattern: 'lunge', family: 'lunge', difficulty: 1, impact: 'low' },
  { id: 'reverse-lunge', icon: '🦿', title: 'Zancada atrás corta', cue: 'Da un paso hacia atrás, baja con control y vuelve al centro.', easier: 'Acorta el paso o usa apoyo.', swapWith: 'supported-split-squat', needs: 'none', focus: ['fuerza', 'activar'], areas: ['knees'], minExperience: 'intermedio', pattern: 'lunge', family: 'lunge', difficulty: 2, impact: 'low' },
  { id: 'step-up', icon: '🪜', title: 'Subida al step', cue: 'Sube al step con un pie, estabiliza y baja con control.', easier: 'Usa un step más bajo y apoyo cercano.', swapWith: 'supported-split-squat', needs: 'none', focus: ['fuerza', 'activar'], areas: ['knees'], equipment: ['stepBox'], minIntensity: 'suave', pattern: 'lunge', family: 'lunge', difficulty: 2, impact: 'low' },
  { id: 'walking-lunge', icon: '🚶', title: 'Zancadas caminando', cue: 'Avanza con zancadas controladas, manteniendo el tronco estable.', easier: 'Vuelve a zancada atrás o usa apoyo.', swapWith: 'reverse-lunge', needs: 'none', focus: ['fuerza', 'activar'], areas: ['knees'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'lunge', family: 'lunge', difficulty: 3, impact: 'medium' },
  { id: 'db-reverse-lunge', icon: '🏋️', title: 'Zancada atrás con mancuernas', cue: 'Sostén las mancuernas a los lados y realiza una zancada atrás estable.', easier: 'Hazla sin carga o con apoyo.', swapWith: 'reverse-lunge', needs: 'none', focus: ['fuerza'], areas: ['knees'], equipment: ['dumbbells'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'lunge', family: 'lunge', difficulty: 4, impact: 'low' },
  { id: 'db-step-up', icon: '🏋️', title: 'Step-up con mancuernas', cue: 'Sube al cajón sosteniendo las mancuernas sin impulsarte con la pierna de abajo.', easier: 'Quita la carga o baja la altura.', swapWith: 'step-up', needs: 'none', focus: ['fuerza'], areas: ['knees'], equipment: ['dumbbells', 'stepBox'], minExperience: 'intermedio', minIntensity: 'alta', pattern: 'lunge', family: 'lunge', difficulty: 4, impact: 'low' },

  // Horizontal + vertical push
  { id: 'wall-press', icon: '🧱', title: 'Flexión en pared', cue: 'Acerca el pecho a la pared con el cuerpo alineado y empuja para volver.', easier: 'Acércate más a la pared.', swapWith: 'incline-push', needs: 'none', focus: ['equilibrado', 'fuerza'], areas: ['shoulders', 'wrists'], pattern: 'push', family: 'horizontal-push', difficulty: 1, impact: 'low' },
  { id: 'incline-push', icon: '💪', title: 'Flexión inclinada', cue: 'Apoya las manos en una superficie firme y baja el pecho con control.', easier: 'Usa una superficie más alta.', swapWith: 'wall-press', needs: 'chair', focus: ['fuerza'], areas: ['shoulders', 'wrists'], pattern: 'push', family: 'horizontal-push', difficulty: 2, impact: 'low' },
  { id: 'knee-pushup', icon: '💪', title: 'Flexión con rodillas apoyadas', cue: 'Desde rodillas, mantén el tronco alineado y baja con control.', easier: 'Vuelve a flexión inclinada.', swapWith: 'incline-push', needs: 'floor', focus: ['fuerza'], areas: ['shoulders', 'wrists', 'lowerBack'], minIntensity: 'moderada', pattern: 'push', family: 'horizontal-push', difficulty: 2, impact: 'low' },
  { id: 'pushup', icon: '💪', title: 'Flexión de brazos', cue: 'Mantén el cuerpo alineado, baja el pecho y empuja el suelo.', easier: 'Apoya rodillas o usa inclinación.', swapWith: 'knee-pushup', needs: 'floor', focus: ['fuerza'], areas: ['shoulders', 'wrists', 'lowerBack'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'push', family: 'horizontal-push', difficulty: 3, impact: 'low' },
  { id: 'db-floor-press', icon: '🏋️', title: 'Press de pecho en suelo con mancuernas', cue: 'Boca arriba, baja los codos hasta tocar suavemente el suelo y empuja.', easier: 'Usa menos recorrido o una mancuerna a la vez.', swapWith: 'wall-press', needs: 'floor', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['dumbbells'], minIntensity: 'moderada', pattern: 'push', family: 'horizontal-push', difficulty: 3, impact: 'low' },
  { id: 'db-bench-press', icon: '🏋️', title: 'Press banca con mancuernas', cue: 'En banco estable, baja las mancuernas con control y empuja.', easier: 'Cambia a press en suelo.', swapWith: 'db-floor-press', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['dumbbells', 'bench'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'push', family: 'horizontal-push', difficulty: 4, impact: 'low' },
  { id: 'machine-chest-press', icon: '⚙️', title: 'Press de pecho en máquina', cue: 'Empuja las asas sin bloquear los codos y vuelve con control.', easier: 'Reduce resistencia o recorrido.', swapWith: 'wall-press', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['machine'], minIntensity: 'moderada', pattern: 'push', family: 'horizontal-push', difficulty: 2, impact: 'low' },
  { id: 'suspension-push', icon: '🪢', title: 'Press en suspensión', cue: 'Inclina el cuerpo en las correas y empuja manteniendo el tronco estable.', easier: 'Ponte más vertical.', swapWith: 'incline-push', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists', 'lowerBack'], equipment: ['suspension'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'push', family: 'horizontal-push', difficulty: 3, impact: 'low' },
  { id: 'band-overhead-press', icon: '➰', title: 'Press sobre cabeza con banda', cue: 'Pisa la banda y empuja hacia arriba sin arquear la espalda.', easier: 'Reduce tensión o rango.', swapWith: 'reach', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'lowerBack'], equipment: ['band'], minIntensity: 'suave', pattern: 'push', family: 'vertical-push', difficulty: 2, impact: 'low' },
  { id: 'db-shoulder-press', icon: '🏋️', title: 'Press de hombros con mancuernas', cue: 'Empuja las mancuernas arriba sin perder la posición del tronco.', easier: 'Hazlo sentado o con una carga que controles.', swapWith: 'band-overhead-press', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'lowerBack'], equipment: ['dumbbells'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'push', family: 'vertical-push', difficulty: 3, impact: 'low' },
  { id: 'machine-shoulder-press', icon: '⚙️', title: 'Press de hombros en máquina', cue: 'Empuja las asas arriba y vuelve sin perder control.', easier: 'Reduce resistencia y recorrido.', swapWith: 'band-overhead-press', needs: 'none', focus: ['fuerza'], areas: ['shoulders'], equipment: ['machine'], minIntensity: 'moderada', pattern: 'push', family: 'vertical-push', difficulty: 2, impact: 'low' },
  { id: 'kb-single-arm-press', icon: '🔔', title: 'Press unilateral con kettlebell', cue: 'Empuja una kettlebell arriba con el tronco estable y alterna lados.', easier: 'Usa banda o press con dos manos.', swapWith: 'band-overhead-press', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'lowerBack'], equipment: ['kettlebell'], minExperience: 'avanzado', minIntensity: 'alta', pattern: 'push', family: 'vertical-push', difficulty: 4, impact: 'low' },

  // Pull
  { id: 'standing-scapular-retraction', icon: '🪽', title: 'Retracción escapular de pie', cue: 'Lleva suavemente los hombros atrás y abajo sin arquear la espalda.', easier: 'Reduce el recorrido y relaja entre repeticiones.', swapWith: 'band-row', needs: 'none', focus: ['fuerza', 'movilidad', 'equilibrado'], areas: ['shoulders'], pattern: 'pull', family: 'horizontal-pull', difficulty: 1, impact: 'low' },
  { id: 'band-row', icon: '➰', title: 'Remo con banda', cue: 'Lleva los codos hacia atrás sin elevar los hombros.', easier: 'Reduce tensión o recorrido.', swapWith: 'standing-scapular-retraction', needs: 'none', focus: ['fuerza', 'equilibrado'], areas: ['shoulders'], equipment: ['band'], minIntensity: 'suave', pattern: 'pull', family: 'horizontal-pull', difficulty: 2, impact: 'low' },
  { id: 'seated-band-row', icon: '🪑', title: 'Remo sentado con banda', cue: 'Sentado, tira de la banda hacia el torso con el pecho abierto.', easier: 'Reduce la tensión.', swapWith: 'band-row', needs: 'chair', focus: ['fuerza'], areas: ['shoulders'], equipment: ['band'], minIntensity: 'suave', pattern: 'pull', family: 'horizontal-pull', difficulty: 1, impact: 'low' },
  { id: 'cable-row', icon: '🎛️', title: 'Remo en polea', cue: 'Tira del agarre hacia el torso y vuelve sin encoger los hombros.', easier: 'Reduce resistencia o recorrido.', swapWith: 'band-row', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'lowerBack'], equipment: ['cable'], minIntensity: 'moderada', pattern: 'pull', family: 'horizontal-pull', difficulty: 2, impact: 'low' },
  { id: 'machine-row', icon: '⚙️', title: 'Remo en máquina', cue: 'Tira de las asas hacia ti y vuelve con control.', easier: 'Reduce resistencia.', swapWith: 'band-row', needs: 'none', focus: ['fuerza'], areas: ['shoulders'], equipment: ['machine'], minIntensity: 'moderada', pattern: 'pull', family: 'horizontal-pull', difficulty: 2, impact: 'low' },
  { id: 'db-row', icon: '💪', title: 'Remo con mancuernas', cue: 'Inclina el tronco desde la cadera y lleva las mancuernas hacia los costados.', easier: 'Reduce recorrido o haz un brazo con apoyo.', swapWith: 'band-row', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'lowerBack'], equipment: ['dumbbells'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'pull', family: 'horizontal-pull', difficulty: 3, impact: 'low' },
  { id: 'suspension-row', icon: '🪢', title: 'Remo en suspensión', cue: 'Inclina el cuerpo y tira del pecho hacia las asas manteniendo el tronco firme.', easier: 'Ponte más vertical.', swapWith: 'band-row', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'lowerBack'], equipment: ['suspension'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'pull', family: 'horizontal-pull', difficulty: 3, impact: 'low' },
  { id: 'band-pulldown', icon: '➰', title: 'Jalón con banda', cue: 'Tira de la banda hacia el pecho sin encoger los hombros.', easier: 'Usa menos tensión.', swapWith: 'band-row', needs: 'none', focus: ['fuerza'], areas: ['shoulders'], equipment: ['band'], minIntensity: 'suave', pattern: 'pull', family: 'vertical-pull', difficulty: 1, impact: 'low' },
  { id: 'lat-pulldown', icon: '🎛️', title: 'Jalón al pecho en polea', cue: 'Lleva la barra hacia la parte alta del pecho y vuelve con control.', easier: 'Reduce resistencia.', swapWith: 'band-pulldown', needs: 'none', focus: ['fuerza'], areas: ['shoulders'], equipment: ['cable'], minIntensity: 'moderada', pattern: 'pull', family: 'vertical-pull', difficulty: 2, impact: 'low' },
  { id: 'assisted-pullup', icon: '⚙️', title: 'Dominada asistida en máquina', cue: 'Sube el pecho con ayuda de la máquina y baja con control.', easier: 'Aumenta la asistencia.', swapWith: 'lat-pulldown', needs: 'none', focus: ['fuerza'], areas: ['shoulders'], equipment: ['machine'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'pull', family: 'vertical-pull', difficulty: 3, impact: 'low' },
  { id: 'pullup-negative', icon: '🧗', title: 'Descenso de dominada', cue: 'Empieza arriba con apoyo seguro y baja lentamente.', easier: 'Usa jalón o asistencia.', swapWith: 'lat-pulldown', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['pullupBar'], minExperience: 'avanzado', minIntensity: 'alta', pattern: 'pull', family: 'vertical-pull', difficulty: 4, impact: 'low' },
  { id: 'pullup', icon: '🧗', title: 'Dominada', cue: 'Tira del cuerpo hacia la barra y baja con control completo.', easier: 'Usa una variante asistida.', swapWith: 'pullup-negative', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['pullupBar'], minExperience: 'avanzado', minIntensity: 'alta', pattern: 'pull', family: 'vertical-pull', difficulty: 5, impact: 'low' },

  // Core / carries
  { id: 'breathing', icon: '😌', title: 'Respiración de cierre', cue: 'Baja el ritmo y respira cómodo, sin aguantar el aire.', easier: 'Respira a tu ritmo natural.', swapWith: 'dead-bug', needs: 'none', focus: ['movilidad', 'equilibrado'], areas: [], pattern: 'core', family: 'core-stability', difficulty: 1, impact: 'low' },
  { id: 'dead-bug', icon: '🪲', title: 'Dead bug', cue: 'Boca arriba, alterna brazo y pierna sin despegar la espalda de una posición cómoda.', easier: 'Mueve solo brazos o solo piernas.', swapWith: 'breathing', needs: 'floor', focus: ['fuerza', 'equilibrado'], areas: ['lowerBack'], pattern: 'core', family: 'core-stability', difficulty: 1, impact: 'low' },
  { id: 'bird-dog', icon: '🧭', title: 'Extensión en cuatro apoyos', cue: 'Alarga brazo y pierna contrarios, vuelve y cambia de lado.', easier: 'Mueve solo una extremidad.', swapWith: 'dead-bug', needs: 'floor', focus: ['fuerza', 'movilidad'], areas: ['shoulders', 'wrists', 'lowerBack'], minExperience: 'intermedio', pattern: 'core', family: 'core-stability', difficulty: 2, impact: 'low' },
  { id: 'plank-knees', icon: '📏', title: 'Plancha con rodillas', cue: 'Mantén el tronco firme con rodillas apoyadas.', easier: 'Haz intervalos más cortos.', swapWith: 'dead-bug', needs: 'floor', focus: ['fuerza'], areas: ['shoulders', 'wrists', 'lowerBack'], minIntensity: 'suave', pattern: 'core', family: 'plank', difficulty: 2, impact: 'low' },
  { id: 'plank', icon: '📏', title: 'Plancha alta', cue: 'Mantén el cuerpo estable desde manos y pies durante el intervalo.', easier: 'Apoya rodillas.', swapWith: 'plank-knees', needs: 'floor', focus: ['fuerza'], areas: ['shoulders', 'wrists', 'lowerBack'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'core', family: 'plank', difficulty: 3, impact: 'low' },
  { id: 'side-plank-knees', icon: '📐', title: 'Plancha lateral con rodillas', cue: 'Apoya antebrazo y rodillas, eleva la cadera y mantén.', easier: 'Reduce el tiempo o baja la cadera.', swapWith: 'dead-bug', needs: 'floor', focus: ['fuerza'], areas: ['shoulders', 'lowerBack'], minIntensity: 'suave', pattern: 'core', family: 'side-plank', difficulty: 2, impact: 'low' },
  { id: 'side-plank', icon: '📐', title: 'Plancha lateral', cue: 'Apoya antebrazo y pies, eleva la cadera y mantén el cuerpo alineado.', easier: 'Apoya rodillas.', swapWith: 'side-plank-knees', needs: 'floor', focus: ['fuerza'], areas: ['shoulders', 'lowerBack'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'core', family: 'side-plank', difficulty: 4, impact: 'low' },
  { id: 'band-pallof', icon: '➰', title: 'Pallof press con banda', cue: 'Empuja la banda al frente evitando que el torso rote.', easier: 'Acércate al anclaje.', swapWith: 'dead-bug', needs: 'none', focus: ['fuerza', 'equilibrado'], areas: ['shoulders'], equipment: ['band'], minIntensity: 'suave', pattern: 'core', family: 'anti-rotation', difficulty: 2, impact: 'low' },
  { id: 'cable-pallof', icon: '🎛️', title: 'Pallof press en polea', cue: 'Empuja el agarre al frente manteniendo la pelvis y el torso estables.', easier: 'Reduce resistencia.', swapWith: 'band-pallof', needs: 'none', focus: ['fuerza'], areas: ['shoulders'], equipment: ['cable'], minIntensity: 'moderada', pattern: 'core', family: 'anti-rotation', difficulty: 3, impact: 'low' },
  { id: 'db-farmer-carry', icon: '🧳', title: 'Caminata del granjero con mancuernas', cue: 'Camina erguido con una mancuerna en cada mano y pasos controlados.', easier: 'Reduce distancia o cambia a marcha sin carga.', swapWith: 'march', needs: 'none', focus: ['fuerza', 'activar'], areas: ['shoulders', 'wrists'], equipment: ['dumbbells'], minIntensity: 'moderada', pattern: 'core', family: 'carry', difficulty: 3, impact: 'low' },
  { id: 'kb-suitcase-carry', icon: '🧳', title: 'Caminata maleta con kettlebell', cue: 'Camina con la kettlebell a un lado sin inclinar el tronco; cambia de mano.', easier: 'Reduce distancia o cambia a marcha.', swapWith: 'march', needs: 'none', focus: ['fuerza', 'activar'], areas: ['shoulders', 'wrists', 'lowerBack'], equipment: ['kettlebell'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'core', family: 'carry', difficulty: 3, impact: 'low' },

  { id: 'heel-raise', icon: '🦶', title: 'Elevación de talones', cue: 'Sube a las puntas de los pies, pausa breve y baja con control.', easier: 'Usa una silla o pared como apoyo.', swapWith: 'calf-release', needs: 'none', focus: ['equilibrado', 'fuerza'], areas: [], pattern: 'lunge', family: 'calf-strength', difficulty: 1, impact: 'low' },
  { id: 'weighted-heel-raise', icon: '🏋️', title: 'Elevación de talones con mancuernas', cue: 'Sostén las mancuernas a los lados y eleva los talones con control.', easier: 'Hazla sin carga y con apoyo.', swapWith: 'heel-raise', needs: 'none', focus: ['fuerza'], areas: ['wrists'], equipment: ['dumbbells'], minIntensity: 'moderada', pattern: 'lunge', family: 'calf-strength', difficulty: 3, impact: 'low' },

  // Conditioning / locomotion
  { id: 'march', icon: '🚶', title: 'Marcha activa', cue: 'Marcha en el sitio con pasos firmes y brazos sueltos.', easier: 'Haz pasos más bajos y usa apoyo.', swapWith: 'toe-tap', needs: 'none', focus: ['equilibrado', 'activar'], areas: ['knees'], pattern: 'conditioning', family: 'locomotion', difficulty: 1, impact: 'low' },
  { id: 'side-step', icon: '↔️', title: 'Pasos laterales continuos', cue: 'Muévete de lado a lado manteniendo un ritmo cómodo.', easier: 'Acorta el paso y usa apoyo.', swapWith: 'march', needs: 'none', focus: ['equilibrado', 'activar'], areas: ['knees'], pattern: 'conditioning', family: 'locomotion', difficulty: 1, impact: 'low' },
  { id: 'toe-tap', icon: '👟', title: 'Toques al frente', cue: 'Toca el suelo al frente con un pie y alterna lados.', easier: 'Haz el toque más cerca.', swapWith: 'march', needs: 'none', focus: ['activar', 'movilidad', 'equilibrado'], areas: ['knees'], pattern: 'conditioning', family: 'locomotion', difficulty: 1, impact: 'low' },
  { id: 'knee-lift', icon: '🦵', title: 'Rodillas alternadas', cue: 'Eleva una rodilla y luego la otra de forma continua.', easier: 'Levanta menos o cambia a toques.', swapWith: 'toe-tap', needs: 'none', focus: ['activar', 'equilibrado'], areas: ['knees'], pattern: 'conditioning', family: 'locomotion', difficulty: 2, impact: 'low' },
  { id: 'squat-reach', icon: '⚡', title: 'Sentadilla + alcance', cue: 'Haz una sentadilla corta y al subir lleva los brazos arriba.', easier: 'Reduce profundidad y alcance.', swapWith: 'march', needs: 'none', focus: ['activar', 'equilibrado'], areas: ['knees', 'shoulders', 'lowerBack'], pattern: 'conditioning', family: 'locomotion', difficulty: 2, impact: 'medium' },
  { id: 'weighted-vest-march', icon: '🎽', title: 'Marcha con chaleco lastrado', cue: 'Marcha con postura erguida usando solo la carga que ya registraste.', easier: 'Quita el chaleco.', swapWith: 'march', needs: 'none', focus: ['activar', 'fuerza'], areas: ['knees', 'lowerBack'], equipment: ['weightedVest'], minIntensity: 'moderada', pattern: 'conditioning', family: 'locomotion', difficulty: 3, impact: 'low' },
  { id: 'jump-rope-basic', icon: '🪢', title: 'Salto de cuerda básico', cue: 'Haz saltos bajos y relajados, manteniendo un ritmo controlable.', easier: 'Simula la cuerda sin salto o vuelve a marcha.', swapWith: 'march', needs: 'none', focus: ['activar'], areas: ['knees'], equipment: ['jumpRope'], minExperience: 'intermedio', minIntensity: 'alta', pattern: 'conditioning', family: 'jump-rope', difficulty: 3, impact: 'high' },
  { id: 'medicine-ball-slam', icon: '🏐', title: 'Slam con balón medicinal', cue: 'Eleva el balón y llévalo al suelo con control del tronco; recupera la postura antes de repetir.', easier: 'Reduce amplitud o cambia a sentadilla + alcance.', swapWith: 'squat-reach', needs: 'none', focus: ['activar', 'fuerza'], areas: ['shoulders', 'lowerBack'], equipment: ['medicineBall'], minExperience: 'intermedio', minIntensity: 'alta', pattern: 'conditioning', family: 'power', difficulty: 4, impact: 'medium' },

  { id: 'barbell-deadlift', icon: '🏋️', title: 'Peso muerto con barra', cue: 'Desde una posición estable, despega la barra del suelo extendiendo cadera y rodillas con control.', easier: 'Reduce carga o cambia a peso muerto con kettlebell.', swapWith: 'kb-deadlift', needs: 'none', focus: ['fuerza'], areas: ['knees', 'lowerBack', 'wrists'], equipment: ['barbell'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'hinge', family: 'hinge', difficulty: 4, impact: 'low' },

  // Trainer-board additions (only clearly readable movements)
  { id: 'barbell-bench-press', icon: '🏋️', title: 'Press banca con barra', cue: 'En banco estable, baja la barra con control y empuja sin perder la posición de hombros.', easier: 'Reduce carga o cambia a press con mancuernas en suelo.', swapWith: 'db-floor-press', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['barbell', 'bench'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'push', family: 'horizontal-push', difficulty: 4, impact: 'low' },
  { id: 'db-incline-press', icon: '🏋️', title: 'Press inclinado con mancuernas', cue: 'En banco inclinado, baja las mancuernas con control y empuja manteniendo el tronco estable.', easier: 'Reduce inclinación o cambia a press en suelo.', swapWith: 'db-floor-press', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['dumbbells', 'bench'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'push', family: 'horizontal-push', difficulty: 4, impact: 'low' },
  { id: 'parallel-dip', icon: '💪', title: 'Fondos en paralelas', cue: 'Desciende entre las paralelas solo en un rango controlado y empuja para volver.', easier: 'Reduce profundidad o usa una variante asistida.', swapWith: 'incline-push', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['parallelBars'], minExperience: 'avanzado', minIntensity: 'alta', pattern: 'push', family: 'horizontal-push', difficulty: 5, impact: 'low' },
  { id: 'barbell-close-grip-press', icon: '🏋️', title: 'Press cerrado con barra', cue: 'Usa un agarre más cerrado que en el press banca y mantén los codos controlados.', easier: 'Cambia a press normal o flexión inclinada.', swapWith: 'barbell-bench-press', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['barbell', 'bench'], minExperience: 'avanzado', minIntensity: 'alta', pattern: 'push', family: 'horizontal-push', difficulty: 5, impact: 'low' },
  { id: 'band-triceps-extension', icon: '➰', title: 'Extensión de tríceps con banda', cue: 'Extiende los codos contra la banda sin mover los hombros.', easier: 'Reduce tensión o recorrido.', swapWith: 'wall-press', needs: 'none', focus: ['fuerza'], areas: ['shoulders'], equipment: ['band'], minIntensity: 'suave', pattern: 'push', family: 'triceps', difficulty: 2, impact: 'low' },
  { id: 'cable-triceps-extension', icon: '🎛️', title: 'Extensión de tríceps en polea', cue: 'Extiende los codos hacia abajo y vuelve con control sin balancear el torso.', easier: 'Reduce resistencia.', swapWith: 'band-triceps-extension', needs: 'none', focus: ['fuerza'], areas: ['shoulders'], equipment: ['cable'], minIntensity: 'moderada', pattern: 'push', family: 'triceps', difficulty: 3, impact: 'low' },
  { id: 'db-triceps-extension', icon: '🏋️', title: 'Extensión de tríceps con mancuerna', cue: 'Extiende los codos con una carga que puedas controlar sin arquear la espalda.', easier: 'Usa banda o menor rango.', swapWith: 'band-triceps-extension', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'lowerBack'], equipment: ['dumbbells'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'push', family: 'triceps', difficulty: 3, impact: 'low' },
  { id: 'db-biceps-curl', icon: '💪', title: 'Curl de bíceps con mancuernas', cue: 'Flexiona los codos sin balancear el tronco y baja con control.', easier: 'Reduce la carga o alterna un brazo.', swapWith: 'band-row', needs: 'none', focus: ['fuerza'], areas: ['wrists'], equipment: ['dumbbells'], minIntensity: 'suave', pattern: 'pull', family: 'biceps', difficulty: 2, impact: 'low' },
  { id: 'barbell-biceps-curl', icon: '🏋️', title: 'Curl de bíceps con barra', cue: 'Flexiona los codos manteniendo el torso quieto y baja la barra con control.', easier: 'Cambia a mancuernas o banda.', swapWith: 'db-biceps-curl', needs: 'none', focus: ['fuerza'], areas: ['wrists'], equipment: ['barbell'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'pull', family: 'biceps', difficulty: 3, impact: 'low' },
  { id: 'suspension-biceps-curl', icon: '🪢', title: 'Curl de bíceps en TRX', cue: 'Inclina el cuerpo en las correas y flexiona los codos sin perder la línea del tronco.', easier: 'Ponte más vertical.', swapWith: 'db-biceps-curl', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['suspension'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'pull', family: 'biceps', difficulty: 3, impact: 'low' },
  { id: 'barbell-row', icon: '🏋️', title: 'Remo con barra', cue: 'Desde una bisagra estable, lleva la barra hacia el torso y vuelve con control.', easier: 'Usa mancuernas o una variante con apoyo.', swapWith: 'db-row', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'lowerBack', 'wrists'], equipment: ['barbell'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'pull', family: 'horizontal-pull', difficulty: 4, impact: 'low' },
  { id: 'renegade-row', icon: '🏋️', title: 'Remo en plancha alta', cue: 'Desde plancha alta, rema una mancuerna alternando lados y limita la rotación del tronco.', easier: 'Apoya rodillas o cambia a remo con apoyo.', swapWith: 'db-row', needs: 'floor', focus: ['fuerza'], areas: ['shoulders', 'wrists', 'lowerBack'], equipment: ['dumbbells'], minExperience: 'avanzado', minIntensity: 'alta', pattern: 'pull', family: 'horizontal-pull', difficulty: 5, impact: 'low' },
  { id: 'barbell-upright-row', icon: '🏋️', title: 'Remo al mentón con barra', cue: 'Eleva la barra solo hasta un rango cómodo para los hombros y baja con control.', easier: 'Reduce rango o cambia a remo normal.', swapWith: 'barbell-row', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['barbell'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'pull', family: 'vertical-pull', difficulty: 3, impact: 'low' },
  { id: 'band-hamstring-curl', icon: '➰', title: 'Curl femoral con banda', cue: 'Flexiona la rodilla contra la banda manteniendo la cadera estable.', easier: 'Reduce tensión o recorrido.', swapWith: 'bridge', needs: 'floor', focus: ['fuerza'], areas: ['knees'], equipment: ['band'], minIntensity: 'suave', pattern: 'hinge', family: 'hinge', difficulty: 2, impact: 'low' },
  { id: 'kb-front-raise', icon: '🔔', title: 'Elevación frontal con kettlebell', cue: 'Eleva la kettlebell al frente hasta un rango cómodo y baja con control.', easier: 'Reduce rango o usa una carga más controlable.', swapWith: 'reach', needs: 'none', focus: ['fuerza'], areas: ['shoulders', 'wrists'], equipment: ['kettlebell'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'push', family: 'vertical-push', difficulty: 3, impact: 'low' },
  { id: 'shoulder-tap-plank', icon: '🤚', title: 'Toques de hombro en plancha', cue: 'Desde plancha alta, toca un hombro con la mano contraria alternando y controla la rotación.', easier: 'Apoya rodillas o separa más los pies.', swapWith: 'plank-knees', needs: 'floor', focus: ['fuerza', 'activar'], areas: ['shoulders', 'wrists', 'lowerBack'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'core', family: 'plank', difficulty: 3, impact: 'low' },
  { id: 'hollow-hold', icon: '🌙', title: 'Hollow hold', cue: 'Mantén una posición compacta boca arriba sin perder el control de la zona lumbar.', easier: 'Flexiona más las rodillas o acerca los brazos.', swapWith: 'dead-bug', needs: 'floor', focus: ['fuerza'], areas: ['lowerBack'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'core', family: 'core-stability', difficulty: 3, impact: 'low' },
  { id: 'mountain-climber', icon: '⛰️', title: 'Mountain climbers', cue: 'Desde plancha, alterna rodillas hacia delante manteniendo el tronco estable.', easier: 'Hazlo lento o con manos elevadas.', swapWith: 'march', needs: 'floor', focus: ['activar'], areas: ['shoulders', 'wrists', 'knees', 'lowerBack'], minExperience: 'intermedio', minIntensity: 'moderada', pattern: 'conditioning', family: 'locomotion', difficulty: 3, impact: 'medium' },
  { id: 'jumping-jack', icon: '⭐', title: 'Jumping jacks', cue: 'Abre y cierra piernas y brazos con un ritmo que puedas mantener.', easier: 'Haz step jacks sin salto.', swapWith: 'side-step', needs: 'none', focus: ['activar'], areas: ['knees', 'shoulders'], minIntensity: 'moderada', pattern: 'conditioning', family: 'locomotion', difficulty: 2, impact: 'high' },
  { id: 'squat-jump', icon: '⚡', title: 'Sentadilla + salto', cue: 'Haz una sentadilla corta y despega suavemente, aterrizando con control.', easier: 'Haz sentadilla + alcance sin salto.', swapWith: 'squat-reach', needs: 'none', focus: ['activar', 'fuerza'], areas: ['knees', 'lowerBack'], minExperience: 'intermedio', minIntensity: 'alta', pattern: 'conditioning', family: 'power', difficulty: 4, impact: 'high' },
  { id: 'broad-jump', icon: '➡️', title: 'Salto largo', cue: 'Impúlsate hacia delante y aterriza estable antes de repetir.', easier: 'Reduce distancia o cambia a step-up.', swapWith: 'step-up', needs: 'none', focus: ['activar', 'fuerza'], areas: ['knees', 'lowerBack'], minExperience: 'avanzado', minIntensity: 'alta', pattern: 'conditioning', family: 'power', difficulty: 5, impact: 'high' },
  { id: 'burpee', icon: '🔥', title: 'Burpee', cue: 'Combina bajar al suelo y volver a ponerse de pie a un ritmo controlable.', easier: 'Hazlo sin salto o con manos en una superficie elevada.', swapWith: 'squat-reach', needs: 'floor', focus: ['activar'], areas: ['shoulders', 'wrists', 'knees', 'lowerBack'], minExperience: 'intermedio', minIntensity: 'alta', pattern: 'conditioning', family: 'power', difficulty: 5, impact: 'high' },
  { id: 'skipping-low', icon: '🏃', title: 'Skipping bajo', cue: 'Corre suave en el sitio con elevación baja de rodillas y ritmo continuo.', easier: 'Cambia a marcha activa.', swapWith: 'march', needs: 'none', focus: ['activar'], areas: ['knees'], minIntensity: 'moderada', pattern: 'conditioning', family: 'locomotion', difficulty: 2, impact: 'medium' },
  { id: 'battle-rope-waves', icon: '🌊', title: 'Battle rope', cue: 'Genera ondas con las cuerdas manteniendo una postura estable y respiración continua.', easier: 'Reduce velocidad o duración.', swapWith: 'march', needs: 'none', focus: ['activar', 'fuerza'], areas: ['shoulders', 'wrists', 'lowerBack'], equipment: ['battleRope'], minExperience: 'intermedio', minIntensity: 'alta', pattern: 'conditioning', family: 'conditioning-rope', difficulty: 4, impact: 'low' },

  // Mobility / recovery
  { id: 'shoulders', icon: '🙆', title: 'Círculos de hombros', cue: 'Haz círculos lentos con los hombros a un ritmo cómodo.', easier: 'Haz círculos más pequeños.', swapWith: 'reach', needs: 'none', focus: ['equilibrado', 'movilidad'], areas: ['shoulders'], pattern: 'mobility', family: 'shoulder-mobility', difficulty: 1, impact: 'low' },
  { id: 'reach', icon: '🌤️', title: 'Alcances suaves', cue: 'Eleva un brazo y cambia de lado sin forzar el rango.', easier: 'Lleva las manos solo hasta el pecho.', swapWith: 'shoulders', needs: 'none', focus: ['movilidad', 'equilibrado'], areas: ['shoulders'], pattern: 'mobility', family: 'shoulder-mobility', difficulty: 1, impact: 'low' },
  { id: 'band-pull-apart', icon: '➰', title: 'Apertura con banda', cue: 'Con brazos al frente y tensión suave, abre la banda sin forzar.', easier: 'Usa menos tensión o menos recorrido.', swapWith: 'reach', needs: 'none', focus: ['fuerza', 'movilidad'], areas: ['shoulders'], equipment: ['band'], minIntensity: 'suave', pattern: 'mobility', family: 'shoulder-mobility', difficulty: 2, impact: 'low' },
  { id: 'calf-release', icon: '🌿', title: 'Soltar pantorrillas', cue: 'Da un paso atrás, apoya el talón y mantén una tensión suave.', easier: 'Acorta la distancia entre los pies.', swapWith: 'breathing', needs: 'none', focus: ['movilidad', 'equilibrado'], areas: [], pattern: 'mobility', family: 'lower-mobility', difficulty: 1, impact: 'low' },
  { id: 'cat-cow', icon: '🐈', title: 'Gato-vaca', cue: 'En cuatro apoyos, alterna suavemente flexión y extensión de la columna.', easier: 'Reduce el rango.', swapWith: 'breathing', needs: 'floor', focus: ['movilidad'], areas: ['wrists', 'lowerBack'], pattern: 'mobility', family: 'spine-mobility', difficulty: 1, impact: 'low' },
  { id: 'thoracic-rotation', icon: '🌀', title: 'Rotación torácica en suelo', cue: 'Desde una posición estable, rota el torso sin forzar el hombro.', easier: 'Reduce el rango.', swapWith: 'reach', needs: 'floor', focus: ['movilidad'], areas: ['shoulders', 'lowerBack'], pattern: 'mobility', family: 'spine-mobility', difficulty: 2, impact: 'low' },
  { id: 'hip-flexor-stretch', icon: '🌿', title: 'Movilidad de flexor de cadera', cue: 'Desde una posición cómoda, lleva suavemente la pelvis hacia delante.', easier: 'Hazlo de pie con apoyo.', swapWith: 'calf-release', needs: 'floor', focus: ['movilidad'], areas: ['knees', 'lowerBack'], pattern: 'mobility', family: 'lower-mobility', difficulty: 1, impact: 'low' },
  { id: 'foam-roll-calf', icon: '🧻', title: 'Foam roller en pantorrilla', cue: 'Rueda lentamente sobre la pantorrilla sin buscar dolor intenso.', easier: 'Reduce presión y recorrido.', swapWith: 'calf-release', needs: 'floor', focus: ['movilidad'], areas: [], equipment: ['foamRoller'], pattern: 'mobility', family: 'lower-mobility', difficulty: 1, impact: 'low' },
  { id: 'foam-roll-upper-back', icon: '🧻', title: 'Foam roller en espalda alta', cue: 'Apoya la espalda alta sobre el roller y haz recorridos cortos y controlados.', easier: 'Reduce presión o usa movilidad sin roller.', swapWith: 'thoracic-rotation', needs: 'floor', focus: ['movilidad'], areas: ['shoulders'], equipment: ['foamRoller'], pattern: 'mobility', family: 'spine-mobility', difficulty: 1, impact: 'low' },
];

export const MOVE_EXERCISE_BY_ID: Record<string, MoveExercise> = Object.fromEntries(
  MOVE_EXERCISE_LIBRARY.map((exercise) => [exercise.id, exercise]),
);

export function sanitizeExcludedExerciseIds(ids: string[]) {
  return Array.from(new Set(ids.filter((id) => Boolean(MOVE_EXERCISE_BY_ID[id]))));
}
