import { StyleSheet } from 'react-native';
import { colors } from '@/src/theme/colors';

export const moveStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  keyboardShell: { flex: 1 },
  content: { padding: 22, paddingBottom: 148 },
  sessionScroll: { flex: 1 },
  sessionShell: { flexGrow: 1, padding: 22, paddingBottom: 132 },
  eyebrow: { color: '#76AFFF', fontWeight: '800', letterSpacing: 4, fontSize: 14, marginTop: 24 },
  title: { color: colors.text, fontWeight: '900', fontSize: 39, lineHeight: 45, marginTop: 10 },
  copy: { color: colors.muted, fontSize: 16, lineHeight: 24, marginTop: 12 },
  section: { color: '#76AFFF', fontWeight: '800', letterSpacing: 4, fontSize: 13, marginTop: 26, marginBottom: 11 },
  recommendCard: { marginTop: 24, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 26, padding: 18 },
  recommendTop: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  moveIcon: { width: 58, height: 58, borderRadius: 20, backgroundColor: '#12315A', borderWidth: 1, borderColor: '#3477C9', alignItems: 'center', justifyContent: 'center' },
  moveEmoji: { fontSize: 28 },
  recommendEyebrow: { color: '#78B7FF', fontSize: 11, fontWeight: '900', letterSpacing: 2 },
  recommendTitle: { color: colors.text, fontSize: 22, fontWeight: '900', marginTop: 4 },
  recommendCopy: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 5 },
  smallLabel: { color: colors.text, fontSize: 13, fontWeight: '900', marginTop: 20, marginBottom: 10 },
  durationRow: { flexDirection: 'row', gap: 8 },
  duration: { flex: 1, minHeight: 62, borderRadius: 17, backgroundColor: colors.surface2, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' },
  durationActive: { backgroundColor: '#163B68', borderColor: colors.blue },
  durationText: { color: colors.muted, fontSize: 19, fontWeight: '900' },
  durationUnit: { color: colors.muted, fontSize: 10, fontWeight: '800', marginTop: 1 },
  durationTextActive: { color: '#FFFFFF' },
  primaryButton: { marginTop: 18, minHeight: 54, borderRadius: 17, backgroundColor: colors.blue, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  primaryButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '900' },
  disabled: { opacity: 0.45 },
  libraryCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 24, paddingHorizontal: 16 },
  libraryRow: { flexDirection: 'row', gap: 12, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.line },
  libraryRowLast: { borderBottomWidth: 0 },
  libraryIcon: { width: 32, fontSize: 23 },
  libraryTitle: { color: colors.text, fontWeight: '900', fontSize: 14 },
  libraryCopy: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 3 },
  libraryNote: { color: '#71829C', fontSize: 11, lineHeight: 17, paddingVertical: 13 },
  doneTodayCard: { marginTop: 24, backgroundColor: '#0F4039', borderWidth: 1, borderColor: '#2C7569', borderRadius: 22, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 11 },
  doneTodayIcon: { color: '#8FE0CD', fontSize: 24, fontWeight: '900' },
  doneTodayTitle: { color: '#A0E8D7', fontWeight: '900', fontSize: 14 },
  doneTodayCopy: { color: '#A9C9C1', fontSize: 11, lineHeight: 17, marginTop: 3 },
  extraButton: { borderWidth: 1, borderColor: '#367C70', borderRadius: 12, paddingHorizontal: 9, paddingVertical: 8 },
  extraButtonText: { color: '#A0E8D7', fontSize: 10, fontWeight: '900' },
  sessionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', gap: 12, marginTop: 24, marginBottom: 18 },
  sessionHeaderCopy: { flex: 1, minWidth: 0 },
  sessionEyebrow: { color: '#76AFFF', fontWeight: '900', letterSpacing: 3, fontSize: 12 },
  sessionCounter: { color: colors.text, fontWeight: '900', fontSize: 17, lineHeight: 22, marginTop: 5 },
  sessionElapsed: { color: '#79B6FF', fontSize: 15, fontWeight: '900', flexShrink: 0 },
  playerCard: { backgroundColor: '#102A4D', borderWidth: 1, borderColor: '#2A5D99', borderRadius: 28, padding: 20 },
  exerciseIdentity: { alignItems: 'center', justifyContent: 'center', minHeight: 122, paddingHorizontal: 6 },
  playerIcon: { fontSize: 48, lineHeight: 58, textAlign: 'center' },
  playerTitle: { width: '100%', color: colors.text, fontSize: 29, lineHeight: 34, fontWeight: '900', textAlign: 'center', marginTop: 8 },
  playerCopy: { color: '#C6D4E7', fontSize: 15, lineHeight: 22, textAlign: 'center', marginTop: 12 },
  easyBox: { marginTop: 16, backgroundColor: '#0A1F39', borderWidth: 1, borderColor: '#27517F', borderRadius: 16, padding: 12 },
  easyLabel: { color: '#78B7FF', fontSize: 10, fontWeight: '900', letterSpacing: 1.8 },
  easyCopy: { color: '#B9C9DD', fontSize: 12, lineHeight: 18, marginTop: 4 },
  timerBlock: { alignItems: 'center', marginTop: 20 },
  timerLabel: { color: '#79B6FF', fontSize: 11, fontWeight: '900', letterSpacing: 2 },
  timerValue: { color: '#FFFFFF', fontSize: 58, lineHeight: 64, fontWeight: '900', marginTop: 3 },
  phaseTrack: { height: 7, borderRadius: 999, backgroundColor: '#081A31', overflow: 'hidden', marginTop: 7 },
  phaseFill: { height: '100%', borderRadius: 999, backgroundColor: '#72B2FF' },
  overallMeta: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16 },
  overallText: { color: '#94A9C4', fontSize: 11, fontWeight: '800' },
  progressTrack: { height: 5, borderRadius: 999, backgroundColor: '#081A31', overflow: 'hidden', marginTop: 7 },
  progressFill: { height: '100%', borderRadius: 999, backgroundColor: colors.blue },
  changeButton: { minHeight: 46, borderRadius: 15, borderWidth: 1, borderColor: '#3D6D9F', alignItems: 'center', justifyContent: 'center', marginTop: 9 },
  changeButtonText: { color: '#9DCAFF', fontSize: 13, fontWeight: '900' },
  sessionActions: { flexDirection: 'row', gap: 10, marginTop: 13 },
  linkButton: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center' },
  linkText: { color: '#8FBFF5', fontWeight: '900', fontSize: 12 },
  pauseCopy: { color: '#F3CF81', fontSize: 11, lineHeight: 17, textAlign: 'center', marginTop: 6 },
  safetyCopy: { color: '#7F93AD', fontSize: 10, lineHeight: 15, textAlign: 'center', marginTop: 10, marginBottom: 4 },
  finishCard: { marginTop: 24, backgroundColor: colors.surface, borderWidth: 1, borderColor: '#2C7569', borderRadius: 26, padding: 18 },
  finishIcon: { color: '#8FE0CD', fontSize: 35, fontWeight: '900' },
  finishTitle: { color: colors.text, fontSize: 25, fontWeight: '900', marginTop: 7 },
  finishSummary: { color: '#8FE0CD', fontSize: 13, fontWeight: '900', marginTop: 6 },
  finishCopy: { color: colors.text, fontSize: 14, fontWeight: '900', marginTop: 20 },
  feedbackWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  feedbackButton: { minHeight: 42, paddingHorizontal: 12, borderRadius: 13, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface2, alignItems: 'center', justifyContent: 'center' },
  feedbackActive: { borderColor: colors.blue, backgroundColor: '#163B68' },
  feedbackText: { color: colors.muted, fontSize: 12, fontWeight: '800' },
  feedbackTextActive: { color: '#FFFFFF' },
  noteLabel: { color: colors.text, fontSize: 13, fontWeight: '900', marginTop: 18 },
  noteInput: { minHeight: 86, marginTop: 9, borderRadius: 15, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface2, color: colors.text, padding: 12, textAlignVertical: 'top', fontSize: 13 },
  noteButton: { alignSelf: 'flex-start', marginTop: 9, paddingVertical: 7, paddingHorizontal: 2 },
  noteButtonText: { color: '#79B6FF', fontSize: 12, fontWeight: '900' },
  feedbackHint: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 12 },
  secondaryWide: { minHeight: 49, borderRadius: 16, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center', marginTop: 16 },
  secondaryButtonText: { color: colors.text, fontSize: 13, fontWeight: '900' },
  lastCard: { marginTop: 20, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 20, padding: 15 },
  lastLabel: { color: '#7087A6', fontSize: 10, fontWeight: '900', letterSpacing: 1.7 },
  lastValue: { color: colors.text, fontSize: 13, fontWeight: '800', marginTop: 6 },
});
